Repository MSAI3rdTeam5/FootTrafficReport, pull requests merged in 2025-02, with the labels that each got.

#37 Feature/backend PostgreSQL DB 구현, 마이크로 서비스 아키텍처 컨테이너 구현
  backend/Dockerfile
  backend/alembic/versions/6cdfa6c67a61_init.py
  backend/alembic/versions/ab51c61fde9c_init.py
  backend/alembic/versions/ba6656c08701_add_foreign_key_constraint_for_report_.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routes.py
  backend/nginx/mycctv.conf
  backend/requirements.txt
Labels: Priority: High, Status: Review Needed, 성빈

#40 Feature/people detection - DB 추가
  people-detection/src/main.py
Labels: Type: Feature, 나경

#41 docs: 주석 추가
  report-generation/chan/data_generation.ipynb
  report-generation/chan/data_genetation_long.ipynb
  report-generation/chan/data_processing.py
  report-generation/chan/gpt_response.py
  report-generation/chan/main.py
  report-generation/chan/prompt.py
  report-generation/chan/visualization.py
Labels: Priority: Low, Status: Pending

#43 chore: 파일 위치 재구성
  .gitignore
  report-generation/__pycache__/data_processing.cpython-312.pyc
  report-generation/__pycache__/gpt_response.cpython-312.pyc
  report-generation/__pycache__/visualization.cpython-312.pyc
  report-generation/data_graph/age_group_values_1739415955.png
  report-generation/data_graph/gender_values_pie_chart_with_labels_1739415956.png
  report-generation/data_graph/time_values_morning_afternoon_lines_1739415956.png
  report-generation/data_graph/weekday_values_1739415955.png
  report-generation/src/main.py
  report-generation/visualization.py
Labels: Priority: High

#53 Feature/backend Celery(스케줄링) + Redis(브로커)를 이용하여 DB 저장 기간 관리 / 1시간 주기로 Person_count 테이블 집계 기능
  .gitignore
  backend/app/aggregate.py
  backend/app/cleanup.py
  backend/celery_app.py
  backend/requirements.txt
  backend/tasks.py
Labels: Type: Feature, Status: Review Needed, 성빈

#62 test: PR 테스트
  people-detection/src/utils/Evaluate.py
Labels: Priority: High

#67 Feature/chatbot
  chatbot/src/main.py
Labels: Type: Feature, Status: Review Needed, 현준

#72 hotfix <- main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .gitmessage.txt
  README.md
  backend/test.py
  chatbot/test.py
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/tailwind.config.js
  frontend/vite.config.js
  people-detection/test.py
  report-generation/chan/__pycache__/data_processing.cpython-312.pyc
  report-generation/chan/__pycache__/gpt_response.cpython-312.pyc
  report-generation/chan/__pycache__/visualization.cpython-312.pyc
  report-generation/chan/data/Female_weight.csv
  report-generation/chan/data/Mon,Wed,Fri_weighted.csv
  report-generation/chan/data/no_weight.csv
  report-generation/chan/data/weekend_weighted.csv
  report-generation/chan/data/youth_weight.csv
  report-generation/chan/data_generation.ipynb
  report-generation/chan/data_genetation_long.ipynb
  report-generation/chan/data_processing.py
  report-generation/chan/gpt_response.py
  report-generation/chan/main.py
  report-generation/chan/prompt.py
  report-generation/chan/visualization.py
  report-generation/chan/yearly_data/decrease_trend_year_data.csv
  report-generation/chan/yearly_data/office_covid_simulation_data.csv
  report-generation/chan/yearly_data/weekend_year_data.csv
  report-generation/hyunjun/test.py
  report-generation/test.py
  report-generation/test2.py
Labels: Status: Completed

#75 hotfix <- people-detection
  people-detection/src/main.py
  people-detection/test.py
Labels: Status: Completed, 나경, 승우, 여경

#78 hotfix <- Hong
  frontend/.gitignore
  frontend/client/dist/index.html
  frontend/client/node_modules/.package-lock.json
  frontend/client/node_modules/.vite/deps/react-dom_client.js.map
  frontend/client/node_modules/.vite/deps/react-router-dom.js.map
  frontend/client/node_modules/.vite/deps/react_jsx-dev-runtime.js
  frontend/client/node_modules/.vite/deps/react_jsx-dev-runtime.js.map
  frontend/client/node_modules/.vite/deps/react_jsx-runtime.js
  frontend/client/node_modules/.vite/deps/react_jsx-runtime.js.map
  frontend/client/package-lock.json
  frontend/client/public/videos/01_에스컬레이터.mp4
  frontend/client/public/videos/05_seoul.mp4
  frontend/client/src/pages/123.txt
  frontend/client/src/pages/CCTVMonitoring.jsx
  frontend/client/src/pages/Monitor.jsx
  frontend/client/src/pages/test.jsx
  frontend/package.json
Labels: Status: Completed, 승우
